[36m--[0m Using CATKIN_DEVEL_PREFIX: /home/lattinone/Damiano/progetto/devel/.private/display_map
[36m--[0m Using CMAKE_PREFIX_PATH: /home/lattinone/Damiano/progetto/devel;/opt/ros/noetic
[36m--[0m This workspace overlays: /home/lattinone/Damiano/progetto/devel;/opt/ros/noetic
[36m--[0m Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3")
[36m--[0m Using PYTHON_EXECUTABLE: /usr/bin/python3
[36m--[0m Using Debian Python package layout
[36m--[0m Using empy: /usr/lib/python3/dist-packages/em.py
[36m--[0m Using CATKIN_ENABLE_TESTING: ON
[36m--[0m Call enable_testing()
[36m--[0m Using CATKIN_TEST_RESULTS_DIR: /home/lattinone/Damiano/progetto/build/display_map/test_results
[36m--[0m Forcing gtest/gmock from source, though one was otherwise available.
[36m--[0m Found gtest sources under '/usr/src/googletest': gtests will be built
[36m--[0m Found gmock sources under '/usr/src/googletest': gmock will be built
[36m--[0m Found PythonInterp: /usr/bin/python3 (found version "3.8.10")
[36m--[0m Using Python nosetests: /usr/bin/nosetests3
[36m--[0m catkin 0.8.10
[36m--[0m BUILD_SHARED_LIBS is on
[36m--[0m Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
[31m[1mCMake Error[0m at /opt/ros/noetic/share/catkin/cmake/catkin_package.cmake:196 (message):
  catkin_package() the catkin package 'cv_bridge' has been find_package()-ed
  but is not listed as a build dependency in the package.xml
[36mCall Stack (most recent call first):[0m
  /opt/ros/noetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  CMakeLists.txt:107 (catkin_package)


[36m--[0m Configuring incomplete, errors occurred!
See also "/home/lattinone/Damiano/progetto/build/display_map/CMakeFiles/CMakeOutput.log".
See also "/home/lattinone/Damiano/progetto/build/display_map/CMakeFiles/CMakeError.log".
make: *** [Makefile:784: cmake_check_build_system] Error 1
